In [26]:
import Base

In [19]:
n = 10
table = zeros(Int64, n, n)
for i=1:n, j=1:n
    table[i,j] = 2^(i-1) * 3^(j-1)
end
@show table

table = [1 3 9 27 81 243 729 2187 6561 19683; 2 6 18 54 162 486 1458 4374 13122 39366; 4 12 36 108 324 972 2916 8748 26244 78732; 8 24 72 216 648 1944 5832 17496 52488 157464; 16 48 144 432 1296 3888 11664 34992 104976 314928; 32 96 288 864 2592 7776 23328 69984 209952 629856; 64 192 576 1728 5184 15552 46656 139968 419904 1259712; 128 384 1152 3456 10368 31104 93312 279936 839808 2519424; 256 768 2304 6912 20736 62208 186624 559872 1679616 5038848; 512 1536 4608 13824 41472 124416 373248 1119744 3359232 10077696]


10×10 Matrix{Int64}:
   1     3     9     27     81     243     729     2187     6561     19683
   2     6    18     54    162     486    1458     4374    13122     39366
   4    12    36    108    324     972    2916     8748    26244     78732
   8    24    72    216    648    1944    5832    17496    52488    157464
  16    48   144    432   1296    3888   11664    34992   104976    314928
  32    96   288    864   2592    7776   23328    69984   209952    629856
  64   192   576   1728   5184   15552   46656   139968   419904   1259712
 128   384  1152   3456  10368   31104   93312   279936   839808   2519424
 256   768  2304   6912  20736   62208  186624   559872  1679616   5038848
 512  1536  4608  13824  41472  124416  373248  1119744  3359232  10077696

In [32]:
t2 = table / 3

10×10 Matrix{Float64}:
   0.333333    1.0     3.0     9.0  …    2187.0          6561.0
   0.666667    2.0     6.0    18.0       4374.0         13122.0
   1.33333     4.0    12.0    36.0       8748.0         26244.0
   2.66667     8.0    24.0    72.0      17496.0         52488.0
   5.33333    16.0    48.0   144.0      34992.0        104976.0
  10.6667     32.0    96.0   288.0  …   69984.0        209952.0
  21.3333     64.0   192.0   576.0     139968.0        419904.0
  42.6667    128.0   384.0  1152.0     279936.0        839808.0
  85.3333    256.0   768.0  2304.0     559872.0             1.67962e6
 170.667     512.0  1536.0  4608.0          1.11974e6       3.35923e6

In [33]:
t3 = Base.log.(2, t2)

10×10 Matrix{Float64}:
 -1.58496   0.0   1.58496   3.16993   4.75489  …   9.50978  11.0947  12.6797
 -0.584963  1.0   2.58496   4.16993   5.75489     10.5098   12.0947  13.6797
  0.415037  2.0   3.58496   5.16993   6.75489     11.5098   13.0947  14.6797
  1.41504   3.0   4.58496   6.16993   7.75489     12.5098   14.0947  15.6797
  2.41504   4.0   5.58496   7.16993   8.75489     13.5098   15.0947  16.6797
  3.41504   5.0   6.58496   8.16993   9.75489  …  14.5098   16.0947  17.6797
  4.41504   6.0   7.58496   9.16993  10.7549      15.5098   17.0947  18.6797
  5.41504   7.0   8.58496  10.1699   11.7549      16.5098   18.0947  19.6797
  6.41504   8.0   9.58496  11.1699   12.7549      17.5098   19.0947  20.6797
  7.41504   9.0  10.585    12.1699   13.7549      18.5098   20.0947  21.6797